name = "mintservices420"
main = "worker.js"
compatibility_date = "2025-03-07"

assets = { directory = "./public", binding = "ASSETS", html_handling = "force-trailing-slash", not_found_handling = "404-page" }



